export const GET_TRENDING_MOVIES = 'GET_TRENDING_MOVIES';
export const GET_SEARCH_MOVIES = 'GET_SEARCH_MOVIES';
export const SET_MOVIE_DETAIL = 'SET_MOVIE_DETAIL';
export const GET_LATEST_MOVIES = 'GET_LATEST_MOVIES';